import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex("order_logs").del();
    await knex("addons").del();
    await knex("meals").del();
    await knex("orders").del();
    await knex("calculated_orders").del();
    await knex("order_types").del();
    await knex("brands").del();

    // Define UUIDs for consistent relationships
    const brandIds = {
        jollofCo: '550e8400-e29b-41d4-a716-446655440001',
        pizzaHub: '550e8400-e29b-41d4-a716-446655440002',
        burgerKing: '550e8400-e29b-41d4-a716-446655440003',
    };

    const orderTypeIds = {
        card: '550e8400-e29b-41d4-a716-446655440010',
        cash: '550e8400-e29b-41d4-a716-446655440011',
        transfer: '550e8400-e29b-41d4-a716-446655440012',
    };

    const calculatedOrderIds = {
        order1: '550e8400-e29b-41d4-a716-446655440020',
        order2: '550e8400-e29b-41d4-a716-446655440021',
        order3: '550e8400-e29b-41d4-a716-446655440022',
        order4: '550e8400-e29b-41d4-a716-446655440023',
        order5: '550e8400-e29b-41d4-a716-446655440024',
    };

    const orderIds = {
        order1: '550e8400-e29b-41d4-a716-446655440030',
        order2: '550e8400-e29b-41d4-a716-446655440031',
        order3: '550e8400-e29b-41d4-a716-446655440032',
        order4: '550e8400-e29b-41d4-a716-446655440033',
        order5: '550e8400-e29b-41d4-a716-446655440034',
    };

    const mealIds = {
        pepperRice: '550e8400-e29b-41d4-a716-446655440040',
        jollofRice: '550e8400-e29b-41d4-a716-446655440041',
        margheritaPizza: '550e8400-e29b-41d4-a716-446655440042',
        pepperoniPizza: '550e8400-e29b-41d4-a716-446655440043',
        chickenBurger: '550e8400-e29b-41d4-a716-446655440044',
        beefBurger: '550e8400-e29b-41d4-a716-446655440045',
        friedRice: '550e8400-e29b-41d4-a716-446655440046',
        veggiepizza: '550e8400-e29b-41d4-a716-446655440047',
    };

    // Insert Brands
    await knex("brands").insert([
        {
            id: brandIds.jollofCo,
            name: "Jollof & Co.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: brandIds.pizzaHub,
            name: "Pizza Hub",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: brandIds.burgerKing,
            name: "Burger Palace",
            created_at: new Date(),
            updated_at: new Date(),
        },
    ]);

    // Insert Order Types
    await knex("order_types").insert([
        {
            id: orderTypeIds.card,
            name: "CARD",
            description: "Credit/Debit Card Payment",
            isActive: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: orderTypeIds.cash,
            name: "CASH",
            description: "Cash on Delivery",
            isActive: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: orderTypeIds.transfer,
            name: "TRANSFER",
            description: "Bank Transfer",
            isActive: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
    ]);

    // Insert Calculated Orders
    await knex("calculated_orders").insert([
        {
            id: calculatedOrderIds.order1,
            totalAmount: 26785.00,
            freeDelivery: false,
            deliveryFee: 900.00,
            serviceCharge: 0.00,
            addressDetails: JSON.stringify({
                city: "Lekki",
                name: "Current",
                address_line: "Lekki, Lagos, Nigeria",
                building_number: "No. 15"
            }),
            lat: "6.453235649711961",
            lng: "3.542877760780109",
            cokitchenPolygonId: "s2",
            userId: "user-001",
            cokitchenId: "kitchen-001",
            pickup: false,
            prevPrice: 15030.00,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: calculatedOrderIds.order2,
            totalAmount: 18500.00,
            freeDelivery: true,
            deliveryFee: 0.00,
            serviceCharge: 500.00,
            addressDetails: JSON.stringify({
                city: "Victoria Island",
                name: "Office",
                address_line: "Victoria Island, Lagos, Nigeria",
                building_number: "Block A, Floor 5"
            }),
            lat: "6.428055555555555",
            lng: "3.422222222222222",
            cokitchenPolygonId: "s1",
            userId: "user-002",
            cokitchenId: "kitchen-002",
            pickup: false,
            prevPrice: 18000.00,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: calculatedOrderIds.order3,
            totalAmount: 32200.00,
            freeDelivery: false,
            deliveryFee: 1200.00,
            serviceCharge: 800.00,
            addressDetails: JSON.stringify({
                city: "Ikeja",
                name: "Home",
                address_line: "Ikeja GRA, Lagos, Nigeria",
                building_number: "22B"
            }),
            lat: "6.595138888888889",
            lng: "3.340277777777778",
            cokitchenPolygonId: "s3",
            userId: "user-003",
            cokitchenId: "kitchen-001",
            pickup: true,
            prevPrice: 30200.00,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: calculatedOrderIds.order4,
            totalAmount: 15750.00,
            freeDelivery: false,
            deliveryFee: 750.00,
            serviceCharge: 0.00,
            addressDetails: JSON.stringify({
                city: "Surulere",
                name: "Friend's Place",
                address_line: "Surulere, Lagos, Nigeria",
                building_number: "88"
            }),
            lat: "6.495833333333333",
            lng: "3.361111111111111",
            cokitchenPolygonId: "s4",
            userId: "user-004",
            cokitchenId: "kitchen-003",
            pickup: false,
            prevPrice: 15000.00,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: calculatedOrderIds.order5,
            totalAmount: 24300.00,
            freeDelivery: true,
            deliveryFee: 0.00,
            serviceCharge: 300.00,
            addressDetails: JSON.stringify({
                city: "Ajah",
                name: "Residential",
                address_line: "Ajah, Lagos, Nigeria",
                building_number: "Suite 10"
            }),
            lat: "6.465277777777778",
            lng: "3.564444444444444",
            cokitchenPolygonId: "s5",
            userId: "user-005",
            cokitchenId: "kitchen-002",
            pickup: false,
            prevPrice: 24000.00,
            created_at: new Date(),
            updated_at: new Date(),
        },
    ]);

    // Insert Orders
    await knex("orders").insert([
        {
            id: orderIds.order1,
            userId: "user-001",
            completed: true,
            cancelled: false,
            kitchenCancelled: false,
            kitchenAccepted: true,
            kitchenDispatched: true,
            kitchenDispatchedTime: new Date("2023-05-17T10:38:26.190Z"),
            completedTime: new Date("2023-05-17T11:04:38.450Z"),
            riderId: "rider-001",
            kitchenPrepared: true,
            riderAssigned: true,
            paid: true,
            orderCode: "ORD001",
            orderChange: null,
            calculatedOrderId: calculatedOrderIds.order1,
            orderTypeId: orderTypeIds.card,
            kitchenVerified: true,
            kitchenCompleted: true,
            shopAccepted: true,
            shopPrepared: true,
            noOfMealbagsDelivered: 1,
            noOfDrinksDelivered: 0,
            riderStartedTime: new Date("2023-05-17T10:40:00.000Z"),
            riderStarted: true,
            riderArrivedTime: new Date("2023-05-17T11:00:00.000Z"),
            riderArrived: true,
            isFailedTrip: false,
            failedTripDetails: JSON.stringify({}),
            boxNumber: "TABLE",
            shelfId: null,
            orderTotalAmountHistory: JSON.stringify([
                {
                    time: "2023-05-17T09:47:30.455+00:00",
                    total_amount: 26785
                }
            ]),
            scheduled: false,
            confirmedById: "staff-001",
            completedById: "rider-001",
            scheduledDeliveryDate: null,
            scheduledDeliveryTime: null,
            isHidden: false,
            created_at: new Date("2023-05-17T09:47:30.455Z"),
            updated_at: new Date("2023-05-17T11:04:38.454Z"),
        },
        {
            id: orderIds.order2,
            userId: "user-002",
            completed: false,
            cancelled: false,
            kitchenCancelled: false,
            kitchenAccepted: true,
            kitchenDispatched: false,
            kitchenDispatchedTime: null,
            completedTime: null,
            riderId: "rider-002",
            kitchenPrepared: true,
            riderAssigned: true,
            paid: true,
            orderCode: "ORD002",
            orderChange: null,
            calculatedOrderId: calculatedOrderIds.order2,
            orderTypeId: orderTypeIds.transfer,
            kitchenVerified: true,
            kitchenCompleted: false,
            shopAccepted: true,
            shopPrepared: true,
            noOfMealbagsDelivered: 0,
            noOfDrinksDelivered: 0,
            riderStartedTime: null,
            riderStarted: false,
            riderArrivedTime: null,
            riderArrived: false,
            isFailedTrip: false,
            failedTripDetails: JSON.stringify({}),
            boxNumber: "B001",
            shelfId: "SHELF-A",
            orderTotalAmountHistory: JSON.stringify([
                {
                    time: "2023-05-17T12:30:00.000+00:00",
                    total_amount: 18500
                }
            ]),
            scheduled: false,
            confirmedById: "staff-002",
            completedById: null,
            scheduledDeliveryDate: null,
            scheduledDeliveryTime: null,
            isHidden: false,
            created_at: new Date("2023-05-17T12:30:00.000Z"),
            updated_at: new Date("2023-05-17T13:15:00.000Z"),
        },
        {
            id: orderIds.order3,
            userId: "user-003",
            completed: false,
            cancelled: false,
            kitchenCancelled: false,
            kitchenAccepted: true,
            kitchenDispatched: false,
            kitchenDispatchedTime: null,
            completedTime: null,
            riderId: null,
            kitchenPrepared: false,
            riderAssigned: false,
            paid: true,
            orderCode: "ORD003",
            orderChange: null,
            calculatedOrderId: calculatedOrderIds.order3,
            orderTypeId: orderTypeIds.cash,
            kitchenVerified: false,
            kitchenCompleted: false,
            shopAccepted: true,
            shopPrepared: false,
            noOfMealbagsDelivered: 0,
            noOfDrinksDelivered: 0,
            riderStartedTime: null,
            riderStarted: false,
            riderArrivedTime: null,
            riderArrived: false,
            isFailedTrip: false,
            failedTripDetails: JSON.stringify({}),
            boxNumber: "B002",
            shelfId: "SHELF-B",
            orderTotalAmountHistory: JSON.stringify([
                {
                    time: "2023-05-17T14:45:00.000+00:00",
                    total_amount: 32200
                }
            ]),
            scheduled: true,
            confirmedById: null,
            completedById: null,
            scheduledDeliveryDate: new Date("2023-05-18"),
            scheduledDeliveryTime: new Date("2023-05-18T18:00:00.000Z"),
            isHidden: false,
            created_at: new Date("2023-05-17T14:45:00.000Z"),
            updated_at: new Date("2023-05-17T14:50:00.000Z"),
        },
        {
            id: orderIds.order4,
            userId: "user-004",
            completed: true,
            cancelled: false,
            kitchenCancelled: false,
            kitchenAccepted: true,
            kitchenDispatched: true,
            kitchenDispatchedTime: new Date("2023-05-16T16:20:00.000Z"),
            completedTime: new Date("2023-05-16T17:05:00.000Z"),
            riderId: "rider-003",
            kitchenPrepared: true,
            riderAssigned: true,
            paid: true,
            orderCode: "ORD004",
            orderChange: null,
            calculatedOrderId: calculatedOrderIds.order4,
            orderTypeId: orderTypeIds.card,
            kitchenVerified: true,
            kitchenCompleted: true,
            shopAccepted: true,
            shopPrepared: true,
            noOfMealbagsDelivered: 1,
            noOfDrinksDelivered: 2,
            riderStartedTime: new Date("2023-05-16T16:25:00.000Z"),
            riderStarted: true,
            riderArrivedTime: new Date("2023-05-16T16:55:00.000Z"),
            riderArrived: true,
            isFailedTrip: false,
            failedTripDetails: JSON.stringify({}),
            boxNumber: "C001",
            shelfId: null,
            orderTotalAmountHistory: JSON.stringify([
                {
                    time: "2023-05-16T15:30:00.000+00:00",
                    total_amount: 15750
                }
            ]),
            scheduled: false,
            confirmedById: "staff-003",
            completedById: "rider-003",
            scheduledDeliveryDate: null,
            scheduledDeliveryTime: null,
            isHidden: false,
            created_at: new Date("2023-05-16T15:30:00.000Z"),
            updated_at: new Date("2023-05-16T17:05:00.000Z"),
        },
        {
            id: orderIds.order5,
            userId: "user-005",
            completed: false,
            cancelled: true,
            kitchenCancelled: true,
            kitchenAccepted: false,
            kitchenDispatched: false,
            kitchenDispatchedTime: null,
            completedTime: null,
            riderId: null,
            kitchenPrepared: false,
            riderAssigned: false,
            paid: false,
            orderCode: "ORD005",
            orderChange: JSON.stringify({ reason: "Customer changed mind" }),
            calculatedOrderId: calculatedOrderIds.order5,
            orderTypeId: orderTypeIds.transfer,
            kitchenVerified: false,
            kitchenCompleted: false,
            shopAccepted: false,
            shopPrepared: false,
            noOfMealbagsDelivered: 0,
            noOfDrinksDelivered: 0,
            riderStartedTime: null,
            riderStarted: false,
            riderArrivedTime: null,
            riderArrived: false,
            isFailedTrip: false,
            failedTripDetails: JSON.stringify({}),
            boxNumber: null,
            shelfId: null,
            orderTotalAmountHistory: JSON.stringify([
                {
                    time: "2023-05-15T20:00:00.000+00:00",
                    total_amount: 24300
                }
            ]),
            scheduled: false,
            confirmedById: null,
            completedById: null,
            scheduledDeliveryDate: null,
            scheduledDeliveryTime: null,
            isHidden: false,
            created_at: new Date("2023-05-15T20:00:00.000Z"),
            updated_at: new Date("2023-05-15T20:15:00.000Z"),
        },
    ]);

    // Insert Meals
    await knex("meals").insert([
        {
            id: mealIds.pepperRice,
            name: "Pepper Rice Special",
            new: true,
            brand: JSON.stringify({ id: brandIds.jollofCo, name: "Jollof & Co." }),
            active: true,
            amount: 1550.00,
            images: JSON.stringify([
                "https://d3u7b9fq2opvwp.cloudfront.net/upload-service/1683254602568a1306e1c-1ff3-486f-9e1b-a7057a823213"
            ]),
            alcohol: false,
            itemNo: null,
            summary: null,
            brandId: brandIds.jollofCo,
            calories: "450",
            isAddon: false,
            isCombo: false,
            position: 7,
            quantity: 1,
            homePage: false,
            itemType: "FOOD",
            mealTags: JSON.stringify(["spicy", "rice", "popular"]),
            isDeleted: false,
            orderNote: "",
            description: "White rice wrapped in banana leaves served with special pepper stew",
            minimumAge: "0",
            posistData: JSON.stringify({}),
            availableNo: "INFINITE",
            mealKeywords: JSON.stringify(["pepper", "rice", "special", "spicy"]),
            internalProfit: 0,
            mealCategoryId: "cat-001",
            calculatedOrderId: calculatedOrderIds.order1,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: mealIds.jollofRice,
            name: "Jollof Rice Deluxe",
            new: false,
            brand: JSON.stringify({ id: brandIds.jollofCo, name: "Jollof & Co." }),
            active: true,
            amount: 1800.00,
            images: JSON.stringify([
                "https://example.com/jollof-rice.jpg"
            ]),
            alcohol: false,
            itemNo: "JR001",
            summary: "Classic Nigerian Jollof Rice",
            brandId: brandIds.jollofCo,
            calories: "520",
            isAddon: false,
            isCombo: false,
            position: 1,
            quantity: 1,
            homePage: true,
            itemType: "FOOD",
            mealTags: JSON.stringify(["jollof", "rice", "nigerian", "classic"]),
            isDeleted: false,
            orderNote: "",
            description: "Perfectly seasoned Jollof rice with rich tomato base",
            minimumAge: "0",
            posistData: JSON.stringify({}),
            availableNo: "INFINITE",
            mealKeywords: JSON.stringify(["jollof", "rice", "tomato", "nigerian"]),
            internalProfit: 200,
            mealCategoryId: "cat-001",
            calculatedOrderId: calculatedOrderIds.order2,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: mealIds.margheritaPizza,
            name: "Margherita Pizza",
            new: false,
            brand: JSON.stringify({ id: brandIds.pizzaHub, name: "Pizza Hub" }),
            active: true,
            amount: 2500.00,
            images: JSON.stringify([
                "https://example.com/margherita-pizza.jpg"
            ]),
            alcohol: false,
            itemNo: "MP001",
            summary: "Classic Italian Margherita",
            brandId: brandIds.pizzaHub,
            calories: "680",
            isAddon: false,
            isCombo: false,
            position: 1,
            quantity: 1,
            homePage: true,
            itemType: "FOOD",
            mealTags: JSON.stringify(["pizza", "italian", "cheese", "classic"]),
            isDeleted: false,
            orderNote: "",
            description: "Fresh mozzarella, tomatoes, and basil on crispy crust",
            minimumAge: "0",
            posistData: JSON.stringify({}),
            availableNo: "INFINITE",
            mealKeywords: JSON.stringify(["pizza", "margherita", "mozzarella", "italian"]),
            internalProfit: 500,
            mealCategoryId: "cat-002",
            calculatedOrderId: calculatedOrderIds.order2,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: mealIds.pepperoniPizza,
            name: "Pepperoni Pizza",
            new: false,
            brand: JSON.stringify({ id: brandIds.pizzaHub, name: "Pizza Hub" }),
            active: true,
            amount: 2800.00,
            images: JSON.stringify([
                "https://example.com/pepperoni-pizza.jpg"
            ]),
            alcohol: false,
            itemNo: "PP001",
            summary: "Spicy Pepperoni Pizza",
            brandId: brandIds.pizzaHub,
            calories: "720",
            isAddon: false,
            isCombo: false,
            position: 2,
            quantity: 1,
            homePage: true,
            itemType: "FOOD",
            mealTags: JSON.stringify(["pizza", "pepperoni", "spicy", "meat"]),
            isDeleted: false,
            orderNote: "",
            description: "Classic pepperoni pizza with extra cheese",
            minimumAge: "0",
            posistData: JSON.stringify({}),
            availableNo: "INFINITE",
            mealKeywords: JSON.stringify(["pizza", "pepperoni", "spicy", "cheese"]),
            internalProfit: 600,
            mealCategoryId: "cat-002",
            calculatedOrderId: calculatedOrderIds.order3,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: mealIds.chickenBurger,
            name: "Grilled Chicken Burger",
            new: true,
            brand: JSON.stringify({ id: brandIds.burgerKing, name: "Burger Palace" }),
            active: true,
            amount: 2200.00,
            images: JSON.stringify([
                "https://example.com/chicken-burger.jpg"
            ]),
            alcohol: false,
            itemNo: "CB001",
            summary: "Grilled Chicken Burger",
            brandId: brandIds.burgerKing,
            calories: "580",
            isAddon: false,
            isCombo: false,
            position: 1,
            quantity: 1,
            homePage: false,
            itemType: "FOOD",
            mealTags: JSON.stringify(["burger", "chicken", "grilled", "healthy"]),
            isDeleted: false,
            orderNote: "",
            description: "Juicy grilled chicken breast with fresh vegetables",
            minimumAge: "0",
            posistData: JSON.stringify({}),
            availableNo: "INFINITE",
            mealKeywords: JSON.stringify(["burger", "chicken", "grilled", "healthy"]),
            internalProfit: 400,
            mealCategoryId: "cat-003",
            calculatedOrderId: calculatedOrderIds.order4,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: mealIds.beefBurger,
            name: "Classic Beef Burger",
            new: false,
            brand: JSON.stringify({ id: brandIds.burgerKing, name: "Burger Palace" }),
            active: true,
            amount: 2400.00,
            images: JSON.stringify([
                "https://example.com/beef-burger.jpg"
            ]),
            alcohol: false,
            itemNo: "BB001",
            summary: "Classic Beef Burger",
            brandId: brandIds.burgerKing,
            calories: "650",
            isAddon: false,
            isCombo: false,
            position: 2,
            quantity: 1,
            homePage: true,
            itemType: "FOOD",
            mealTags: JSON.stringify(["burger", "beef", "classic", "juicy"]),
            isDeleted: false,
            orderNote: "",
            description: "100% beef patty with lettuce, tomato, and special sauce",
            minimumAge: "0",
            posistData: JSON.stringify({}),
            availableNo: "INFINITE",
            mealKeywords: JSON.stringify(["burger", "beef", "classic", "sauce"]),
            internalProfit: 450,
            mealCategoryId: "cat-003",
            calculatedOrderId: calculatedOrderIds.order3,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: mealIds.friedRice,
            name: "Special Fried Rice",
            new: false,
            brand: JSON.stringify({ id: brandIds.jollofCo, name: "Jollof & Co." }),
            active: true,
            amount: 1700.00,
            images: JSON.stringify([
                "https://example.com/fried-rice.jpg"
            ]),
            alcohol: false,
            itemNo: "FR001",
            summary: "Special Fried Rice",
            brandId: brandIds.jollofCo,
            calories: "480",
            isAddon: false,
            isCombo: false,
            position: 3,
            quantity: 1,
            homePage: false,
            itemType: "FOOD",
            mealTags: JSON.stringify(["rice", "fried", "vegetables", "special"]),
            isDeleted: false,
            orderNote: "",
            description: "Fried rice with mixed vegetables and protein",
            minimumAge: "0",
            posistData: JSON.stringify({}),
            availableNo: "INFINITE",
            mealKeywords: JSON.stringify(["rice", "fried", "vegetables", "protein"]),
            internalProfit: 300,
            mealCategoryId: "cat-001",
            calculatedOrderId: calculatedOrderIds.order5,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: mealIds.veggiepizza,
            name: "Vegetarian Pizza",
            new: true,
            brand: JSON.stringify({ id: brandIds.pizzaHub, name: "Pizza Hub" }),
            active: true,
            amount: 2600.00,
            images: JSON.stringify([
                "https://example.com/veggie-pizza.jpg"
            ]),
            alcohol: false,
            itemNo: "VP001",
            summary: "Fresh Vegetarian Pizza",
            brandId: brandIds.pizzaHub,
            calories: "620",
            isAddon: false,
            isCombo: false,
            position: 3,
            quantity: 1,
            homePage: false,
            itemType: "FOOD",
            mealTags: JSON.stringify(["pizza", "vegetarian", "healthy", "fresh"]),
            isDeleted: false,
            orderNote: "",
            description: "Fresh vegetables on crispy crust with cheese",
            minimumAge: "0",
            posistData: JSON.stringify({}),
            availableNo: "INFINITE",
            mealKeywords: JSON.stringify(["pizza", "vegetarian", "vegetables", "healthy"]),
            internalProfit: 550,
            mealCategoryId: "cat-002",
            calculatedOrderId: calculatedOrderIds.order4,
            created_at: new Date(),
            updated_at: new Date(),
        },
    ]);

    // Insert Addons
    await knex("addons").insert([
        {
            id: '550e8400-e29b-41d4-a716-446655440050',
            amount: 780.00,
            images: JSON.stringify({}),
            mealId: mealIds.pepperRice,
            isCombo: false,
            position: 6,
            quantity: 1,
            mealData: JSON.stringify({
                id: "extra-portion-001",
                name: "Extra portion",
                active: true,
                amount: "780",
                brandId: brandIds.jollofCo,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "1",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "md1",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440051',
            amount: 2350.00,
            images: JSON.stringify({}),
            mealId: mealIds.pepperRice,
            isCombo: false,
            position: 6,
            quantity: 1,
            mealData: JSON.stringify({
                id: "peppered-turkey-001",
                name: "Peppered Turkey",
                active: true,
                amount: "2350",
                brandId: brandIds.jollofCo,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "2839f8b1-6b20-421c-bdbb-28e70001334f",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "001b1dbf-38ef-462c-b045-598459f03a24",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440052',
            amount: 500.00,
            images: JSON.stringify({}),
            mealId: mealIds.jollofRice,
            isCombo: false,
            position: 1,
            quantity: 1,
            mealData: JSON.stringify({
                id: "extra-sauce-001",
                name: "Extra Sauce",
                active: true,
                amount: "500",
                brandId: brandIds.jollofCo,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "sauce-001",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "sauce-cat-001",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440053',
            amount: 800.00,
            images: JSON.stringify({}),
            mealId: mealIds.margheritaPizza,
            isCombo: false,
            position: 1,
            quantity: 1,
            mealData: JSON.stringify({
                id: "extra-cheese-001",
                name: "Extra Cheese",
                active: true,
                amount: "800",
                brandId: brandIds.pizzaHub,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "cheese-001",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "cheese-cat-001",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440054',
            amount: 1200.00,
            images: JSON.stringify({}),
            mealId: mealIds.pepperoniPizza,
            isCombo: false,
            position: 1,
            quantity: 1,
            mealData: JSON.stringify({
                id: "extra-pepperoni-001",
                name: "Extra Pepperoni",
                active: true,
                amount: "1200",
                brandId: brandIds.pizzaHub,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "pepperoni-001",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "meat-cat-001",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440055',
            amount: 600.00,
            images: JSON.stringify({}),
            mealId: mealIds.chickenBurger,
            isCombo: false,
            position: 1,
            quantity: 1,
            mealData: JSON.stringify({
                id: "fries-001",
                name: "French Fries",
                active: true,
                amount: "600",
                brandId: brandIds.burgerKing,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "fries-001",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "sides-cat-001",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440056',
            amount: 300.00,
            images: JSON.stringify({}),
            mealId: mealIds.beefBurger,
            isCombo: false,
            position: 1,
            quantity: 1,
            mealData: JSON.stringify({
                id: "drink-001",
                name: "Soft Drink",
                active: true,
                amount: "300",
                brandId: brandIds.burgerKing,
                itemType: "DRINK"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "drink-001",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "drinks-cat-001",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440057',
            amount: 1000.00,
            images: JSON.stringify({}),
            mealId: mealIds.friedRice,
            isCombo: false,
            position: 1,
            quantity: 1,
            mealData: JSON.stringify({
                id: "grilled-chicken-001",
                name: "Grilled Chicken",
                active: true,
                amount: "1000",
                brandId: brandIds.jollofCo,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "chicken-001",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "protein-cat-001",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440058',
            amount: 700.00,
            images: JSON.stringify({}),
            mealId: mealIds.veggiepizza,
            isCombo: false,
            position: 1,
            quantity: 1,
            mealData: JSON.stringify({
                id: "extra-veggies-001",
                name: "Extra Vegetables",
                active: true,
                amount: "700",
                brandId: brandIds.pizzaHub,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "veggies-001",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "veggies-cat-001",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440059',
            amount: 400.00,
            images: JSON.stringify({}),
            mealId: mealIds.jollofRice,
            isCombo: false,
            position: 2,
            quantity: 1,
            mealData: JSON.stringify({
                id: "plantain-001",
                name: "Fried Plantain",
                active: true,
                amount: "400",
                brandId: brandIds.jollofCo,
                itemType: "FOOD"
            }),
            posistData: JSON.stringify({}),
            mealAddonId: "plantain-001",
            internalProfit: 0,
            minSelectionNo: "0",
            mealAddonCategoryId: "sides-cat-002",
            created_at: new Date(),
            updated_at: new Date(),
        },
    ]);

    // Insert Order Logs
    await knex("order_logs").insert([
        // Order 1 logs (completed order)
        {
            id: '550e8400-e29b-41d4-a716-446655440060',
            orderId: orderIds.order1,
            description: "Order received in kitchen",
            time: new Date("2023-05-17T09:47:30.455Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440061',
            orderId: orderIds.order1,
            description: "Order accepted by kitchen",
            time: new Date("2023-05-17T09:47:47.716Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440062',
            orderId: orderIds.order1,
            description: "Order completed by kitchen",
            time: new Date("2023-05-17T10:32:32.907Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440063',
            orderId: orderIds.order1,
            description: "Order dispatched by front desk",
            time: new Date("2023-05-17T10:38:26.190Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440064',
            orderId: orderIds.order1,
            description: "Trip Completed By Rider(James)",
            time: new Date("2023-05-17T11:04:38.448Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        // Order 2 logs (in progress)
        {
            id: '550e8400-e29b-41d4-a716-446655440065',
            orderId: orderIds.order2,
            description: "Order received in kitchen",
            time: new Date("2023-05-17T12:30:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440066',
            orderId: orderIds.order2,
            description: "Order accepted by kitchen",
            time: new Date("2023-05-17T12:35:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440067',
            orderId: orderIds.order2,
            description: "Order preparation started",
            time: new Date("2023-05-17T13:00:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        // Order 3 logs (scheduled)
        {
            id: '550e8400-e29b-41d4-a716-446655440068',
            orderId: orderIds.order3,
            description: "Order received and scheduled",
            time: new Date("2023-05-17T14:45:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440069',
            orderId: orderIds.order3,
            description: "Order accepted by kitchen for tomorrow",
            time: new Date("2023-05-17T14:50:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        // Order 4 logs (completed yesterday)
        {
            id: '550e8400-e29b-41d4-a716-446655440070',
            orderId: orderIds.order4,
            description: "Order received in kitchen",
            time: new Date("2023-05-16T15:30:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440071',
            orderId: orderIds.order4,
            description: "Order accepted by kitchen",
            time: new Date("2023-05-16T15:35:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440072',
            orderId: orderIds.order4,
            description: "Order prepared by kitchen",
            time: new Date("2023-05-16T16:15:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440073',
            orderId: orderIds.order4,
            description: "Order dispatched for delivery",
            time: new Date("2023-05-16T16:20:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440074',
            orderId: orderIds.order4,
            description: "Order delivered successfully",
            time: new Date("2023-05-16T17:05:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        // Order 5 logs (cancelled)
        {
            id: '550e8400-e29b-41d4-a716-446655440075',
            orderId: orderIds.order5,
            description: "Order received in kitchen",
            time: new Date("2023-05-15T20:00:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440076',
            orderId: orderIds.order5,
            description: "Order cancelled by customer",
            time: new Date("2023-05-15T20:15:00.000Z"),
            created_at: new Date(),
            updated_at: new Date(),
        },
    ]);
}
